"""
codegen.py — Saral AST → Python Code Generator v4.0
Walks the AST produced by parser.py and emits valid Python.
Produces a source map: every Python line → original Saral line.
"""

import textwrap
from typing import List, Tuple, Dict, Optional, Any
from ast_nodes import *


# ─────────────────────────────────────────────
# STDLIB HEADER (injected once at top)
# ─────────────────────────────────────────────

STDLIB = r'''# === Generated by Saral v4.0 (Parser-based) ===
import sys as _s, math as _m, random as _r
import os as _o, datetime as _dt
import json as _j, csv as _csv
import re as _re, threading as _th
import urllib.request as _ur, textwrap as _tw

_C = {
    "red":"\033[91m","green":"\033[92m","yellow":"\033[93m",
    "blue":"\033[94m","magenta":"\033[95m","cyan":"\033[96m",
    "white":"\033[97m","bold":"\033[1m","reset":"\033[0m",
}
def _color(t,c): print(f"{_C.get(c,'')}{t}{_C['reset']}")
def _progress(cur,tot,w=40):
    p=int(cur/tot*100); d=int(cur/tot*w)
    print(f"\r[{'█'*d+'░'*(w-d)}] {p}% ({cur}/{tot})",end="",flush=True)
    if cur>=tot: print()

def _ai(prompt, data=""):
    try:
        from ai_helper import query
        return query(prompt, data)
    except ImportError:
        return "[AI not available]"

def _rf(p):
    with open(p,"r",encoding="utf-8") as f: return f.read()
def _wf(p,c):
    with open(p,"w",encoding="utf-8") as f: f.write(str(c))
def _af(p,c):
    with open(p,"a",encoding="utf-8") as f: f.write("\n"+str(c))
def _rl(p):
    with open(p,"r",encoding="utf-8") as f:
        return [l.rstrip("\n") for l in f]
def _rcsv(p):
    with open(p,"r",encoding="utf-8",newline="") as f:
        return [dict(r) for r in _csv.DictReader(f)]
def _wcsv(p,d):
    if not d: return
    with open(p,"w",encoding="utf-8",newline="") as f:
        w=_csv.DictWriter(f,fieldnames=d[0].keys())
        w.writeheader(); w.writerows(d)
def _rj(p):
    with open(p,"r",encoding="utf-8") as f: return _j.load(f)
def _wj(p,d):
    with open(p,"w",encoding="utf-8") as f:
        _j.dump(d,f,indent=2,ensure_ascii=False)
def _fetch(url):
    try:
        with _ur.urlopen(_ur.Request(url),timeout=15) as r:
            return r.read().decode()
    except Exception as e: return f"[Fetch error:{e}]"
def _fetchj(url):
    t=_fetch(url)
    try: return _j.loads(t)
    except: return t
def _ask_num(p):
    while True:
        try:
            _v = input(p)
            return float(_v) if '.' in _v else int(_v)
        except: print("  Please enter a valid number.")
def _pad(x,w,d="left"):
    s=str(x)
    if d=="left":   return s.rjust(w)
    if d=="right":  return s.ljust(w)
    if d=="center": return s.center(w)
    return s
def _deep(*args):
    d=args[0]
    for k in args[1:]:
        if isinstance(d,dict): d=d.get(k)
        elif isinstance(d,list): d=d[int(k)]
        else: return None
    return d
def _validate(kind,val,lo=None,hi=None):
    if kind=="email":
        return bool(_re.match(r'^[\w\.-]+@[\w\.-]+\.\w+$',str(val)))
    if kind=="phone":
        return bool(_re.match(r'^[\d\s\+\-\(\)]{7,15}$',str(val)))
    if kind=="number":
        try: float(val); return True
        except: return False
    if kind=="range":
        try: return float(lo)<=float(val)<=float(hi)
        except: return False
    if kind=="not_empty":
        return val is not None and str(val).strip()!=""
    return False
_threads=[]
def _bg(fn,*args):
    t=_th.Thread(target=fn,args=args,daemon=True)
    t.start(); _threads.append(t); return t
def _wait_all():
    for t in _threads: t.join()
    _threads.clear()
def _include(path):
    import importlib.util
    if not _o.path.exists(path):
        print(f"[Include error: '{path}' not found]"); return
    with open(path,"r",encoding="utf-8") as f: src=f.read()
    from pipeline import transpile
    exec(compile(transpile(src),"<included:"+path+">","exec"),globals())

'''


# ─────────────────────────────────────────────
# MATH / STRING FUNCTION MAP
# ─────────────────────────────────────────────

MATH_FN_MAP = {
    "sqrt":     "_m.sqrt",
    "floor":    "_m.floor",
    "ceiling":  "_m.ceil",
    "sin":      lambda a: f"round(_m.sin(_m.radians({a})), 10)",
    "cos":      lambda a: f"round(_m.cos(_m.radians({a})), 10)",
    "tan":      lambda a: f"round(_m.tan(_m.radians({a})), 10)",
    "log":      "_m.log10",
    "absolute": "abs",
    "round":    "round",
    "square":   lambda a: f"(float({a}) ** 2)",
    "cube":     lambda a: f"(float({a}) ** 3)",
}

STRING_OP_MAP = {
    "uppercase": lambda a: f"str({a}).upper()",
    "lowercase": lambda a: f"str({a}).lower()",
    "trimmed":   lambda a: f"str({a}).strip()",
    "reversed":  lambda a: f"str({a})[::-1]",
    "length":    lambda a: f"len({a})",
}

TYPE_MAP = {
    "number":  "int",
    "text":    "str",
    "decimal": "float",
    "boolean": lambda a: f"(str({a}).lower() in ('true','yes','1'))",
}

DATE_MAP = {
    "today":         "_dt.date.today().strftime('%d-%m-%Y')",
    "now":           "_dt.datetime.now().strftime('%d-%m-%Y %H:%M:%S')",
    "current_time":  "_dt.datetime.now().strftime('%H:%M:%S')",
    "current_year":  "_dt.datetime.now().year",
    "current_month": "_dt.datetime.now().month",
    "current_day":   "_dt.datetime.now().day",
}

COLOR_SET = {
    "red","green","yellow","blue","magenta","cyan","white","bold"
}


# ─────────────────────────────────────────────
# CODE GENERATOR CLASS
# ─────────────────────────────────────────────

class CodeGen:
    def __init__(self, source_lines: List[str],
                 filename: str = "<program>"):
        self.source_lines = source_lines
        self.filename     = filename
        self.lines:  List[str] = []
        self.indent: int       = 0
        # source map: python_line_number → saral_line_number
        self.source_map: Dict[int, int] = {}

    # ── helpers ─────────────────────────────

    def emit(self, code: str, saral_line: int = 0):
        """Emit one line of Python code."""
        py_line_num = len(self.lines) + 1
        self.lines.append("    " * self.indent + code)
        if saral_line:
            self.source_map[py_line_num] = saral_line

    def emit_blank(self):
        self.lines.append("")

    def indent_in(self):
        self.indent += 1

    def indent_out(self):
        if self.indent > 0:
            self.indent -= 1

    def python(self) -> str:
        return "\n".join(self.lines)

    # ── expression generator ────────────────

    def gen_expr(self, node: Any) -> str:
        """Convert an expression AST node to Python expression string."""

        if node is None:
            return "None"

        # List of AST nodes = comma-separated args (e.g. call fn with a, b)
        if isinstance(node, list):
            return ", ".join(self.gen_expr(n) for n in node)

        if isinstance(node, NumberLiteral):
            if node.is_int():
                return str(int(node.value))
            return str(node.value)

        if isinstance(node, StringLiteral):
            raw = node.value  # includes quotes
            # convert {var} to f-string if needed
            if node.is_fstring:
                return "f" + raw
            return raw

        if isinstance(node, BoolLiteral):
            return "True" if node.value else "False"

        if isinstance(node, Identifier):
            return node.name

        if isinstance(node, BinaryOp):
            left  = self.gen_expr(node.left)
            right = self.gen_expr(node.right)
            # Fix: negative base with power must be wrapped in parens
            # (-3)^2 = 9 (correct), not -(3^2) = -9 (wrong)
            if node.op == "**":
                # strip outer parens from left if already wrapped
                left_clean = left.strip("()")
                # if left starts with minus, always wrap
                if left.startswith("(-") or left_clean.startswith("-"):
                    return f"(({left}) ** {right})"
                return f"({left} ** {right})"
            return f"({left} {node.op} {right})"

        if isinstance(node, UnaryOp):
            operand = self.gen_expr(node.operand)
            return f"({node.op} {operand})"

        if isinstance(node, MathFnExpr):
            arg = self.gen_expr(node.arg)
            fn  = node.fn
            if fn == "round":
                if node.places is not None:
                    return f"round(float({arg}), {node.places})"
                return f"round(float({arg}))"
            if fn in MATH_FN_MAP:
                mapped = MATH_FN_MAP[fn]
                if callable(mapped):
                    return mapped(arg)
                return f"{mapped}(float({arg}))"
            return f"_{fn}({arg})"

        if isinstance(node, AggregateExpr):
            name = node.list_name
            fn   = node.fn
            if fn == "sum":     return f"sum({name})"
            if fn == "average": return f"(sum({name})/len({name}) if {name} else 0)"
            if fn == "maximum": return f"max({name})"
            if fn == "minimum": return f"min({name})"
            return f"_{fn}({name})"

        if isinstance(node, StringOpExpr):
            arg = self.gen_expr(node.arg)
            op  = node.op
            if op in STRING_OP_MAP:
                return STRING_OP_MAP[op](arg)
            return f"str({arg})"

        if isinstance(node, PadExpr):
            val = self.gen_expr(node.value)
            return f"_pad({val}, {node.width}, '{node.direction}')"

        if isinstance(node, ListOpExpr):
            name = node.list_name
            op   = node.op
            if op == "item":
                idx = self.gen_expr(node.index)
                return f"{name}[int({idx})-1]"
            if op == "items":
                s = self.gen_expr(node.start)
                e = self.gen_expr(node.end)
                return f"{name}[int({s})-1:int({e})]"
            if op == "first":
                n = self.gen_expr(node.start)
                return f"{name}[:int({n})]"
            if op == "last":
                n = self.gen_expr(node.start)
                return f"{name}[-int({n}):]"
            return f"{name}"

        if isinstance(node, DictOpExpr):
            key  = self.gen_expr(node.key)
            return f"{node.dict_name}.get({key})"

        if isinstance(node, DeepGetExpr):
            keys = ", ".join(self.gen_expr(k) for k in node.keys)
            return f"_deep({node.dict_name}, {keys})"

        if isinstance(node, DateExpr):
            kind = node.kind
            return DATE_MAP.get(kind, f"_dt.date.today()")

        if isinstance(node, RandomExpr):
            if node.low and node.high:
                lo = self.gen_expr(node.low)
                hi = self.gen_expr(node.high)
                return f"_r.randint(int({lo}), int({hi}))"
            return "_r.randint(1, 100)"

        if isinstance(node, ResultOfExpr):
            if node.args:
                args = self.gen_expr(node.args)
                return f"{node.fn_name}({args})"
            return f"{node.fn_name}()"

        if isinstance(node, AsTypeExpr):
            val = self.gen_expr(node.value)
            kw  = node.type_kw
            if kw in TYPE_MAP:
                mapped = TYPE_MAP[kw]
                if callable(mapped):
                    return mapped(val)
                return f"{mapped}({val})"
            return val

        if isinstance(node, FStringExpr):
            return f'f"{node.template}"'

        if isinstance(node, PatternCondition):
            pat = self.gen_expr(node.pattern)
            # ensure raw string
            if pat.startswith(("'", '"')) and not pat.startswith(("r'", 'r"')):
                pat = "r" + pat
            return f"bool(_re.search({pat}, {node.var_name}))"

        if isinstance(node, FileExistsCondition):
            path = self.gen_expr(node.path)
            return f"_o.path.exists({path})"

        # fallback
        return repr(node)

    # ── condition generator ─────────────────

    def gen_condition(self, node: Any) -> str:
        """Generate a Python condition string."""
        if isinstance(node, PatternCondition):
            return self.gen_expr(node)
        if isinstance(node, FileExistsCondition):
            return self.gen_expr(node)
        if isinstance(node, BinaryOp):
            if node.op in ("and", "or"):
                left  = self.gen_condition(node.left)
                right = self.gen_condition(node.right)
                return f"({left} {node.op} {right})"
            left  = self.gen_expr(node.left)
            right = self.gen_expr(node.right)
            return f"{left} {node.op} {right}"
        if isinstance(node, UnaryOp) and node.op == "not":
            return f"not ({self.gen_condition(node.operand)})"
        return self.gen_expr(node)

    # ── statement generator ─────────────────

    def gen_stmt(self, node: Stmt):
        """Generate Python for a single statement."""
        ln = node.line_num

        # ── store ─────────────────────────────────────────
        if isinstance(node, StoreStmt):
            val = self.gen_expr(node.value)
            self.emit(f"{node.target} = {val}", ln)
            return

        # ── show ──────────────────────────────────────────
        if isinstance(node, ShowStmt):
            val = self.gen_expr(node.value)
            if node.color and node.color in COLOR_SET:
                self.emit(f"_color({val}, '{node.color}')", ln)
            else:
                self.emit(f"print({val})", ln)
            return

        if isinstance(node, ShowErrorStmt):
            self.emit("print(_saral_err)", ln)
            return

        if isinstance(node, ShowBlankStmt):
            self.emit("print()", ln)
            return

        if isinstance(node, ShowProgressStmt):
            cur = self.gen_expr(node.current)
            tot = self.gen_expr(node.total)
            self.emit(f"_progress({cur}, {tot})", ln)
            return

        # ── ask ───────────────────────────────────────────
        if isinstance(node, AskStmt):
            prompt = self.gen_expr(node.prompt)
            if node.is_number:
                self.emit(f"{node.target} = _ask_num({prompt})", ln)
            else:
                self.emit(f"{node.target} = input({prompt})", ln)
            return

        if isinstance(node, AskAiStmt):
            prompt = self.gen_expr(node.prompt)
            data   = node.data or '""'
            self.emit(f"{node.target} = _ai({prompt}, {data})", ln)
            return

        # ── increase / decrease ───────────────────────────
        if isinstance(node, IncreaseStmt):
            amt = self.gen_expr(node.amount)
            self.emit(f"{node.target} += {amt}", ln)
            return

        if isinstance(node, DecreaseStmt):
            amt = self.gen_expr(node.amount)
            self.emit(f"{node.target} -= {amt}", ln)
            return

        # ── return ────────────────────────────────────────
        if isinstance(node, ReturnStmt):
            if not node.values:
                self.emit("return None", ln)
            elif len(node.values) == 1:
                self.emit(f"return {self.gen_expr(node.values[0])}", ln)
            else:
                vals = ", ".join(self.gen_expr(v) for v in node.values)
                self.emit(f"return {vals}", ln)
            return

        # ── call ──────────────────────────────────────────
        if isinstance(node, CallStmt):
            if node.args:
                args = self.gen_expr(node.args)
                self.emit(f"{node.fn_name}({args})", ln)
            else:
                self.emit(f"{node.fn_name}()", ln)
            return

        if isinstance(node, StoreResultStmt):
            if node.args:
                args = self.gen_expr(node.args)
                self.emit(f"{node.target} = {node.fn_name}({args})", ln)
            else:
                self.emit(f"{node.target} = {node.fn_name}()", ln)
            return

        if isinstance(node, StoreMultipleResultStmt):
            targets = ", ".join(node.targets)
            if node.args:
                args = self.gen_expr(node.args)
                self.emit(f"{targets} = {node.fn_name}({args})", ln)
            else:
                self.emit(f"{targets} = {node.fn_name}()", ln)
            return

        # ── list operations ───────────────────────────────
        if isinstance(node, AddStmt):
            val = self.gen_expr(node.value)
            self.emit(f"{node.target}.append({val})", ln)
            return

        if isinstance(node, RemoveStmt):
            val = self.gen_expr(node.value)
            if node.is_dict:
                self.emit(f"{node.target}.pop({val}, None)", ln)
            else:
                self.emit(f"{node.target}.remove({val})", ln)
            return

        if isinstance(node, MakeListStmt):
            self.emit(f"{node.name} = []", ln)
            return

        if isinstance(node, MakeDictStmt):
            self.emit(f"{node.name} = {{}}", ln)
            return

        if isinstance(node, MakeUniqueStmt):
            self.emit(f"{node.target} = list(dict.fromkeys({node.source}))", ln)
            return

        if isinstance(node, SortStmt):
            rev = "True" if node.reverse else "False"
            self.emit(f"{node.name} = sorted({node.name}, reverse={rev})", ln)
            return

        if isinstance(node, ReverseStmt):
            self.emit(f"{node.name} = {node.name}[::-1]", ln)
            return

        if isinstance(node, SetDictStmt):
            key = self.gen_expr(node.key)
            val = self.gen_expr(node.value)
            self.emit(f"{node.dict_name}[{key}] = {val}", ln)
            return

        if isinstance(node, SetListStmt):
            idx = self.gen_expr(node.index)
            val = self.gen_expr(node.value)
            self.emit(f"{node.list_name}[int({idx})-1] = {val}", ln)
            return

        # ── control flow ──────────────────────────────────
        if isinstance(node, GlobalStmt):
            names = ", ".join(node.names)
            self.emit(f"global {names}", ln)
            return

        if isinstance(node, IncludeStmt):
            path = self.gen_expr(node.path)
            self.emit(f"_include({path})", ln)
            return

        if isinstance(node, UseStmt):
            if node.alias:
                self.emit(f"import {node.library} as {node.alias}", ln)
            else:
                self.emit(f"import {node.library}", ln)
            return

        # ── file I/O ──────────────────────────────────────
        if isinstance(node, WriteFileStmt):
            path    = self.gen_expr(node.path)
            content = self.gen_expr(node.content)
            self.emit(f"_wf({path}, {content})", ln)
            return

        if isinstance(node, AppendFileStmt):
            path    = self.gen_expr(node.path)
            content = self.gen_expr(node.content)
            self.emit(f"_af({path}, {content})", ln)
            return

        if isinstance(node, DeleteFileStmt):
            path = self.gen_expr(node.path)
            self.emit(f"_o.remove({path})", ln)
            return

        if isinstance(node, ReadFileStmt):
            path = self.gen_expr(node.path)
            mode = node.mode
            if mode == "text":
                self.emit(f"{node.target} = _rf({path})", ln)
            elif mode == "lines":
                self.emit(f"{node.target} = _rl({path})", ln)
            elif mode == "csv":
                self.emit(f"{node.target} = _rcsv({path})", ln)
            elif mode == "json":
                self.emit(f"{node.target} = _rj({path})", ln)
            return

        if isinstance(node, WriteCsvStmt):
            path = self.gen_expr(node.path)
            self.emit(f"_wcsv({path}, {node.data})", ln)
            return

        if isinstance(node, WriteJsonStmt):
            path = self.gen_expr(node.path)
            self.emit(f"_wj({path}, {node.data})", ln)
            return

        if isinstance(node, FetchStmt):
            url = self.gen_expr(node.url)
            if node.as_json:
                self.emit(f"{node.target} = _fetchj({url})", ln)
            else:
                self.emit(f"{node.target} = _fetch({url})", ln)
            return

        # ── regex ─────────────────────────────────────────
        if isinstance(node, FindPatternStmt):
            pat = self.gen_expr(node.pattern)
            if pat.startswith(("'",'"')) and not pat.startswith(("r'","r\"")):
                pat = "r" + pat
            self.emit(f"{node.target} = _re.findall({pat}, {node.source})", ln)
            return

        if isinstance(node, ReplacePatternStmt):
            pat = self.gen_expr(node.pattern)
            rep = self.gen_expr(node.replacement)
            if pat.startswith(("'",'"')) and not pat.startswith(("r'","r\"")):
                pat = "r" + pat
            self.emit(f"{node.target} = _re.sub({pat}, {rep}, {node.source})", ln)
            return

        if isinstance(node, ReplaceStrStmt):
            old = self.gen_expr(node.old)
            new = self.gen_expr(node.new)
            self.emit(f"{node.target} = str({node.source}).replace({old}, {new})", ln)
            return

        if isinstance(node, SplitStmt):
            sep = self.gen_expr(node.sep)
            self.emit(f"{node.target} = str({node.source}).split({sep})", ln)
            return

        if isinstance(node, JoinStmt):
            sep = self.gen_expr(node.sep)
            self.emit(f"{node.target} = {sep}.join(str(x) for x in {node.source})", ln)
            return

        # ── validation ────────────────────────────────────
        if isinstance(node, ValidateStmt):
            kind = node.kind
            src  = node.source
            tgt  = node.target
            if kind == "range":
                lo  = self.gen_expr(node.low)
                hi  = self.gen_expr(node.high)
                self.emit(f"{tgt} = _validate('range', {src}, {lo}, {hi})", ln)
            else:
                self.emit(f"{tgt} = _validate('{kind}', {src})", ln)
            return

        # ── json ──────────────────────────────────────────
        if isinstance(node, ParseJsonStmt):
            self.emit(f"{node.target} = _j.loads({node.source})", ln)
            return

        if isinstance(node, ConvertJsonStmt):
            self.emit(f"{node.target} = _j.dumps({node.source}, ensure_ascii=False)", ln)
            return

        # ── concurrency ───────────────────────────────────
        if isinstance(node, RunBackgroundStmt):
            if node.args:
                args = self.gen_expr(node.args)
                self.emit(f"_bg({node.fn_name}, {args})", ln)
            else:
                self.emit(f"_bg({node.fn_name})", ln)
            return

        if isinstance(node, WaitForAllStmt):
            self.emit("_wait_all()", ln)
            return

        # ── utility ───────────────────────────────────────
        if isinstance(node, WaitStmt):
            secs = self.gen_expr(node.seconds)
            self.emit(f"__import__('time').sleep({secs})", ln)
            return

        if isinstance(node, ClearScreenStmt):
            self.emit("_o.system('cls' if _o.name=='nt' else 'clear')", ln)
            return

        if isinstance(node, ExitStmt):
            self.emit("_s.exit(0)", ln)
            return

        if isinstance(node, StopStmt):
            self.emit("break", ln)
            return

        if isinstance(node, SkipStmt):
            self.emit("continue", ln)
            return

        if isinstance(node, RaiseErrorStmt):
            msg = self.gen_expr(node.message)
            self.emit(f"raise Exception({msg})", ln)
            return

        if isinstance(node, CommentStmt):
            self.emit(f"# {node.text}", ln)
            return

        if isinstance(node, FlattenStmt):
            self.emit(
                f"{node.target} = [x for sub in {node.source} "
                f"for x in (sub if isinstance(sub, list) else [sub])]", ln)
            return

        if isinstance(node, MultilineStrStmt):
            import textwrap as tw
            dedented = tw.dedent("\n".join(node.lines))
            escaped  = dedented.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')
            self.emit(f'{node.target} = """{escaped}"""', ln)
            return

        # ── compound statements ───────────────────────────
        if isinstance(node, IfStmt):
            cond = self.gen_condition(node.condition)
            self.emit(f"if {cond}:", ln)
            self.indent_in()
            self._gen_block(node.body)
            self.indent_out()

            for elif_cond, elif_body in node.elseifs:
                c = self.gen_condition(elif_cond)
                self.emit(f"elif {c}:")
                self.indent_in()
                self._gen_block(elif_body)
                self.indent_out()

            if node.else_body is not None:
                self.emit("else:")
                self.indent_in()
                self._gen_block(node.else_body)
                self.indent_out()
            return

        if isinstance(node, RepeatStmt):
            count = self.gen_expr(node.count)
            self.emit(f"for _i in range(int({count})):", ln)
            self.indent_in()
            self._gen_block(node.body)
            self.indent_out()
            return

        if isinstance(node, ForEachStmt):
            iterable = f"reversed({node.iterable})" if node.reverse else node.iterable
            self.emit(f"for {node.var} in {iterable}:", ln)
            self.indent_in()
            self._gen_block(node.body)
            self.indent_out()
            return

        if isinstance(node, CountStmt):
            start = self.gen_expr(node.start)
            end   = self.gen_expr(node.end)
            self.emit(f"for {node.var} in range(int({start}), int({end})+1):", ln)
            self.indent_in()
            self._gen_block(node.body)
            self.indent_out()
            return

        if isinstance(node, WhileStmt):
            cond = self.gen_condition(node.condition)
            self.emit(f"while {cond}:", ln)
            self.indent_in()
            self._gen_block(node.body)
            self.indent_out()
            return

        if isinstance(node, DefineStmt):
            params = []
            for pname, pdefault in node.params:
                if pdefault is not None:
                    params.append(f"{pname}={self.gen_expr(pdefault)}")
                else:
                    params.append(pname)
            param_str = ", ".join(params)
            self.emit(f"def {node.name}({param_str}):", ln)
            self.indent_in()
            if not node.body:
                self.emit("pass")
            else:
                self._gen_block(node.body)
            self.indent_out()
            self.emit_blank()
            return

        if isinstance(node, TryStmt):
            self.emit("try:", ln)
            self.indent_in()
            self._gen_block(node.body)
            self.indent_out()
            self.emit("except Exception as _saral_err:")
            self.indent_in()
            if not node.catch_body:
                self.emit("pass")
            else:
                self._gen_block(node.catch_body)
            self.indent_out()
            return

        if isinstance(node, StoreCsvColumnStmt):
            col = self.gen_expr(node.column)
            self.emit(
                f"{node.target} = [_row.get({col}) for _row in {node.data} "
                f"if isinstance(_row, dict)]", ln)
            return

        # Unknown node type — emit a comment
        self.emit(f"# [codegen: unhandled node {type(node).__name__}]", ln)

    def _gen_block(self, stmts: List[Stmt]):
        """Generate a block of statements."""
        if not stmts:
            self.emit("pass")
            return
        for stmt in stmts:
            self.gen_stmt(stmt)

    # ── main generate ────────────────────────

    def generate(self, program: Program) -> Tuple[str, Dict[int, int]]:
        """
        Generate complete Python source from AST.
        Returns (python_source, source_map).
        source_map: {python_line → saral_line}
        """
        # Emit stdlib header
        for line in STDLIB.splitlines():
            self.lines.append(line)

        self.emit_blank()
        self.emit(f"# === Program: {self.filename} ===")
        self.emit_blank()

        # Generate all statements
        for stmt in program.body:
            self.gen_stmt(stmt)

        return self.python(), self.source_map


# ─────────────────────────────────────────────
# CONVENIENCE FUNCTION
# ─────────────────────────────────────────────

def generate(program: Program, source_lines: List[str],
             filename: str = "<program>") -> Tuple[str, Dict[int, int]]:
    """Generate Python source from an AST."""
    gen = CodeGen(source_lines, filename)
    return gen.generate(program)


# ─────────────────────────────────────────────
# TEST — full pipeline: source → tokens → AST → Python
# ─────────────────────────────────────────────

if __name__ == "__main__":
    from parser import parse

    test_src = """
# Saral v4.0 codegen test
store 10 in price
store price * 2 in double_price
show "Price: {price}" in green
show double_price

if price > 5 and price < 100
    show "in range"
otherwise if price >= 100
    show "too high"
otherwise
    show "too low"
done

repeat 3 times
    show "hello"
done

make list called fruits
add "apple" to fruits
add "mango" to fruits
add "banana" to fruits
sort fruits
store item 1 of fruits in first_fruit
show first_fruit

store sqrt of 144 in sq
store round of 3.14159 to 2 places in pi
show sq
show pi

make dictionary called person
set "name" of person to "Arun"
set "city" of person to "Irinjalakuda"
store value of "name" in person in pname
show pname

define greet using name, title = "Mr"
    show "Hello " + title + " " + name
end

call greet with "Arun"
store result of greet with "Arun" in msg
show msg

count from 1 to 5 as n
    show n
done

try
    store 10 / 0 in bad
catch
    show "Caught division by zero!"
done

store today in date
show date

check that "arun@test.com" is valid email and store in ok
show ok

show "-- Done --" in bold
"""

    # Parse
    ast, parse_errors = parse(test_src)
    if parse_errors:
        print("Parse errors:")
        for e in parse_errors:
            print(f"  {e}")
    else:
        print(f"✅  Parse: {len(ast.body)} statements")

    # Generate
    source_lines = test_src.splitlines()
    python_code, source_map = generate(ast, source_lines)

    print(f"✅  Generated: {len(python_code.splitlines())} Python lines")
    print(f"✅  Source map: {len(source_map)} entries")

    # Compile check
    try:
        compile(python_code, "<test>", "exec")
        print("✅  Python compile: clean")
    except SyntaxError as e:
        print(f"❌  Syntax error: {e}")
        # show offending line
        py_lines = python_code.splitlines()
        if e.lineno:
            print(f"    Line {e.lineno}: {py_lines[e.lineno-1] if e.lineno <= len(py_lines) else '?'}")

    # Execute
    print("\n── Output ────────────────────────────────")
    try:
        exec(compile(python_code, "<test>", "exec"), {})
    except Exception as e:
        print(f"Runtime error: {e}")
    print("──────────────────────────────────────────")
